// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// init
void init(std::string path);
RcppExport SEXP _lantern_init(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    init(path);
    return R_NilValue;
END_RCPP
}
// rcpp_lantern_test
void rcpp_lantern_test();
RcppExport SEXP _lantern_rcpp_lantern_test() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_lantern_test();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lantern_init", (DL_FUNC) &_lantern_init, 1},
    {"_lantern_rcpp_lantern_test", (DL_FUNC) &_lantern_rcpp_lantern_test, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_lantern(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
