# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

init <- function(path) {
    invisible(.Call(`_lantern_init`, path))
}

rcpp_hello_world <- function() {
    .Call(`_lantern_rcpp_hello_world`)
}

