# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_lantern_init <- function(path) {
    invisible(.Call(`_lantern_rcpp_lantern_init`, path))
}

rcpp_lantern_test <- function() {
    invisible(.Call(`_lantern_rcpp_lantern_test`))
}

